/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileDropZone: typeof import('./src/components/FileDropZone.vue')['default']
    IconInput: typeof import('./src/components/IconInput.vue')['default']
    ModelExporter: typeof import('./src/components/ModelExporter.vue')['default']
    ModelRenderer: typeof import('./src/components/ModelRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgTo3D: typeof import('./src/components/SvgTo3D.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
